---
# tasks file for kubernetes

- name: Open ports needed for Kubernetes
  become: yes
  include: ports.yml

- name: Check if kubelet.conf exists
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

- name: Join to cluster if needed
  become: yes
  command: "{{ hostvars[groups[lookup('env', 'STAGE') | lower | default('development', true)][0]]['kubeadm_join_command']['stdout'] }}"
  when: not kubelet_conf.stat.exists
# - name: Enable and check kubelet service
#   systemd:
#     name: kubelet
#     daemon_reload: yes
#     state: started
#     enabled: yes

# - name: Reset Kubernetes component
#   shell: "kubeadm reset --force"
#   register: reset_cluster

# - name: Recreate kube-dns
#   command: kubectl --kubeconfig=.kube.confoi -n kube-system delete pods -l k8s-app=kube-dns
#   delegate_to: "{{ groups['masters'][0] }}"
#   run_once: true
#   ignore_errors: true
