---
# Open ports for use by kubernetes worker nodes

- name: Open worker node ports
  ufw:
    rule: allow
    direction: incoming
    to_port: "{{ item }}"
    proto: tcp
  loop:
    - 10250 # Kubelet API
    - 30000:32767 # NodePort Services
  notify: restart ufw