 
kind: pipeline
name: default

steps:
  - name: apply ansible playbook
    image: plugins/ansible:1
    settings:
      playbook: ansible/playbook.yml
      # galaxy: ansible/requirements.yml
      inventory: ansible/inventory.yml
      private_key:
        from_secret: ANSIBLE_PRIVATE_KEY
    when:
      event:
      - push
      - tag
  
  - name: notify finished
    image: appleboy/drone-discord:1.0.0
    when:
      status:
        - success
        - failure
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: |
        Build {{ build.status }} {{ build.link }}

volumes:
  - name: dockerSock
    host:
      path: /var/run/docker.sock