---
# tasks file for kubernetes

- name: Open ports needed for Kubernetes
  include: ports.yml

- name: Check cluster state
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init.yml
  # when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Copy Calico yml template
  template:
    src: templates/calico/v{{ calico_version }}/manifests/calico.yaml.j2
    dest: ~/calico.yml

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

# command: {{ temp }}/calico.yaml

# kubectl taint nodes --all node-role.kubernetes.io/master-