---
# tasks file for kubernetes

- name: Open ports needed for Kubernetes
  include: ports.yml

- name: Check cluster state
  # Thanks MonadicT
  command: kubeadm token list
  register: kubernetes_init
  ignore_errors: true

- name: Initialise Cluster if doesn't exist
  command: 
    argv:
      - kubeadm
      - init
      - --pod-network-cidr 10.200.0.0/16
      - --apiserver-advertise-address={{ apiserver_advertise_address | default(inventory_hostname) }}
  register: kubernetes_init
  # failed_when: false
  when: kubernetes_init.rc > 0

- name: Copy Calico yml template
  template:
    src: /templates/calico/v{{ calico_version }}/manifests/calico.yml
    dest: ~/calico.yml


# template from /templates/calico/v{{ calico_version }}/manifests/calico.yml
# to {{ temp }}/calico.yml

# command: {{ temp }}/calico.yaml

# kubectl taint nodes --all node-role.kubernetes.io/master-