---
# tasks file for kubernetes

- name: Open ports needed for Kubernetes
  include: ports.yml

- name: Check cluster state
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Deploy kubernetes dashboard into cluster
  command: |
    kubectl --kubeconfig=.kube/config \
        apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 5
  ignore_errors: true
  when: dashboard

- name: Copy Calico yml template
  template:
    src: templates/calico/v{{ calico_version }}/manifests/calico.yaml.j2
    dest: ~/calico.yml

- name: Apply Calico template
  command: kubectl apply -f ~/calico.yaml
  # hosts: group_name[0]
  
- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

# kubectl taint nodes --all node-role.kubernetes.io/master-