---
# tasks file for kubernetes

- name: Open ports needed for Kubernetes
  include: ports.yml

- name: Reset cluster
  include_tasks: reset.yml
  when: reset

- name: Check cluster state
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Copy Calico yml template
  template:
    src: templates/calico/v{{ calico_version }}/manifests/calico.yaml.j2
    dest: "./calico.yaml"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755

- name: Apply Calico template
  command: kubectl apply -f ./calico.yaml

  # hosts: group_name[0]
- name: Enable and check kubelet service
  become: yes
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: Generate kubeadm join command
  become: yes
  command: kubeadm token create --print-join-command --ttl 60m
  register: kubeadm_join_command
# kubectl taint nodes --all node-role.kubernetes.io/master-
