---
# Open ports for use by kubernetes

- name: Open control-plane (master) node ports
  become: yes
  ufw:
    rule: allow
    direction: in
    to_port: "{{ item }}"
    proto: tcp
  loop:
    - "6443" # Kubernetes API server
    - "2379:2380" # etcd server client API
    - "10250" # Kubelet API
    - "10251" # kube-scheduler
    - "10252" # kube-controller-manager
  notify: restart ufw
