---
# tasks file for kubernetes-services


- name: Download NGINX ingress controller config
  get_url:
    url: "{{ item }}"
    dest: /tmp/
    force: yes
  loop:
    - "https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/mandatory.yaml"
    - "https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/provider/baremetal/service-nodeport.yaml"

- name: Install NGINX ingress controller
  k8s:
    state: present
    src: /tmp/{{ item }}
  loop:
    - mandatory.yaml
    - service-nodeport.yaml
