---
- hosts: pve0.kallan.xyz
  gather_facts: False
  tasks:
    - name: Get resource pools
      shell: pvesh ls /pools
      register: pvesh_pools

    - name: Creating a resource pool
      shell: pvesh create /pools -poolid "{{ server_resource_pool }}" --Comment "{{ server_resource_pool_comment }}"
      when: pvesh_pools.stdout.find(server_resource_pool) == -1
      run_once: yes

    - name: Downloading the Debian qcow2 image.
      get_url:
        url: "{{ qcow2_image }}"
        dest: "{{ qcow2_download_location }}image.qcow2"

    - name: Copy public key to proxmox host
      copy:
        src: "{{ k8s_ssh_key_local }}"
        dest: "{{ k8s_ssh_key_remote }}"

    - name: Reset VMs
      ignore_errors: yes
      block:
        - name: Stop VMs
          shell: qm stop {{ server_id }}

        - name: Delete existing VMs.
          shell: qm destroy {{ server_id }}

    - name: Creating the VMs.
      shell: >
        qm create {{ server_id }}
        --agent 1
        --cores {{ server_cpu }}
        --memory {{ server_mem }} 
        --name {{ server_hostname }}
        --nameserver {{ k8s_dns_server }}
        --net0 "virtio,bridge={{ k8s_network_bridge }}"
        --onboot 1
        --ostype "l26"
        --pool {{ server_resource_pool }}
        --searchdomain {{ k8s_search_domain }}
        --sshkeys {{ k8s_ssh_key_remote }}
        --boot c 
        --bootdisk scsi0
        --scsihw virtio-scsi-pci
        --serial0 /dev/tty0

      # --ipconfig0 "gw={{ k8s_gateway }},ip={{ server_ip }}{{ k8s_subnet }}"
    - name: Importing the qcow2 image as a disk.
      shell: qm importdisk {{ server_id }} {{ qcow2_download_location }}image.qcow2 {{ k8s_stg }}

    - name: Configuring the VM Hardware.
      shell: >
        qm set {{ server_id }}
        --scsi0 {{ k8s_stg }}:vm-{{ server_id }}-disk-0
        --ide2 {{ k8s_stg }}:cloudinit

    - name: Resizing the disk.
      shell: qm resize {{ server_id }} scsi0 {{ k8s_size }}

    - name: Mount MergerFS Data Disks by passthrough
      command: qm set {{ server_id }} -scsi{{ item.key }} {{ item.source }}
      loop: "{{ mergerfs_data_disks }}"

    # - name: Mount MergerFS Parity Disks by passthrough
    #   command: qm set {{ server_id }} -scsi{{ item.key }} {{ item.source }}
    #   loop: "{{ mergerfs_parity_disks }}"

    - name: Starting the VMs.
      shell: qm start {{ server_id }}

    - name: Waiting for the VMs to become available.
      wait_for:
        host: "{{ server_hostname }}"
        port: 22
        msg: "VMs did not become available after 5 minutes. Network error?"

# scsi-0QEMU_QEMU_HARDDISK_drive-scsi{{ item.key }}-part1
# loop: "{{ mergerfs_data_disks }}"