---
- hosts: k8s_cluster
  gather_facts: no
  tasks:
    - name: Wait for nodes to become ready for connection
      wait_for_connection:
        # delay: 30 # seconds until begin checking

    - name: Wait for automatic updates to finish
      shell: |
        timeout=$(($(date +%s) + 600))

        while pgrep apt > /dev/null; do
          
            time=$(date +%s)

            if [[ $time -ge $timeout ]];
            then
                exit 1
            fi

            sleep 1
        done;
        exit 0

    - name: Perform package upgrade
      become: yes
      apt:
        name: "*"
        state: latest

    - name: Install base packages
      become: yes
      apt:
        name: "{{ item }}"
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - haveged
        - gnupg2
        - openssl
        - python-pip
        - qemu-guest-agent
        - software-properties-common
        # - iptables
        - arptables
        - ebtables

    - name: Configure legacy iptables
      become: yes
      alternatives:
        name: "{{ item }}"
        path: /usr/sbin/{{ item }}-legacy
      loop:
        - iptables
        - ip6tables
        - arptables
        - ebtables

    - name: Adding the necessary GPG keys.
      become: yes
      apt_key:
        url: "{{ item }}"
      loop:
        - "https://download.docker.com/linux/debian/gpg"
        - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

    - name: Adding the necessary Apt repositories.
      become: yes
      apt_repository:
        repo: "{{ item }}"
        update_cache: yes
      loop:
        - "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
        - "deb https://apt.kubernetes.io/ kubernetes-xenial main"

    - name: Install kubeadm, kubelet and kubectl
      become: yes
      update_cache: yes
      cache_valid_time: 3600
      apt:
        name: "{{ item }}"
      loop:
        - docker-ce
        - kubelet
        - kubeadm
        - kubectl

    - name: Install Python dependencies
      become: yes
      pip:
        name: "{{ item }}"
        extra_args: --upgrade
      loop:
        - kubernetes
        - openshift
        - pyyaml
        - requests

    - name: Enable Systemd modules
      become: yes
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - docker
        - kubelet
        - qemu-guest-agent
        - haveged

    - name: Remove dhcp from eth0
      become: yes
      lineinfile:
        path: /etc/network/interfaces
        line: iface eth0 inet dhcp
        state: absent

    - name: Reboot OS
      become: yes
      reboot:
