---
- hosts: proxmox_servers
  gather_facts: no
  tasks:
    - name: Remove Proxmox Enterprise sources
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Add free repository to sources
      apt_repository:
        repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
        state: present
        filename: pve-no-subscription

    - name: Remove License Prompt
      replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: "data.status \\!== \\'Active\\'"
        replace: "false"
        backup: yes
      register: license_check

    - name: restart pveproxy
      service:
        name: pveproxy
        state: restarted
      when: license_check.changed
