---
- name: Set Hostname
  hosts: all
  handlers:
    - include: ./kubernetes-master/handlers/handlers.yml
  tasks:
    - ping:
    
    - name: Change hostname
      become: yes
      hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
      notify:
        - restart hostname
        - restart systemd-logind
      when: ansible_hostname != inventory_hostname

    - name: Modify /etc/hosts
      become: yes
      lineinfile:
        dest: /etc/hosts
        regex: '^127\.0\.1\.1'
        line: "127.0.1.1 localhost {{ inventory_hostname }} {{ inventory_hostname_short }}"
        state: present
        backup: yes
      notify:
        - restart hostname
        - restart systemd-logind