all:
  children:
    proxmox_servers:
      hosts:
        pve[0:3].kallan.xyz:
    nodes:
      children:
        kubernetes:
          children:
            node_master:
              hosts:
                charles.kallan.xyz:
                  node_id: "4011"
                  node_ip: "192.168.2.201"
                  hypervisor: pve1.kallan.xyz
                kingston.kallan.xyz:
                  node_id: "4012"
                  node_ip: "192.168.2.202"
                  hypervisor: pve2.kallan.xyz
              vars:
                node_cpu: "4"
                node_mem_min: "4096"
                node_mem_max: "8192"
                POSTGRES_PASSWORD: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
                k3s_datastore_endpoint: "postgres://kubernetes:{{ POSTGRES_PASSWORD }}@core.kallan.xyz:5432/k3s?sslmode=disable"
            node_worker:
              hosts:
                parkwood.kallan.xyz:
                  node_id: "4014"
                  node_ip: "192.168.2.204"
                  hypervisor: pve0.kallan.xyz
              vars:
                node_cpu: "2"
                node_mem_min: "2048"
                node_mem_max: "4096"
          vars:
            node_resource_pool: Kubernetes
            node_resource_pool_comment: "Kubernetes Control Plane"
            k3s_endpoint: kubernetes.kallan.xyz
            first_master: charles.kallan.xyz
      vars:
        node_search_domain: kallan.xyz

        qcow2_image: "https://cdimage.debian.org/cdimage/openstack/archive/10.4.1-20200515/debian-10.4.1-20200515-openstack-amd64.qcow2"
        qcow2_download_location: "/tmp/"

        node_ssh_key_local: "~/.ssh/xyz.kallan.pve.kubernetes.pub"
        node_ssh_key_remote: "/root/.ssh/xyz.kallan.pve.kubernetes.pub"

        ansible_user: debian
        node_disk_size: "30G"
        node_stg: local-lvm

        # Subnet Sizes
        node_subnet: "/24"

        # Network
        node_network_bridge: "vmbr0"
        node_gateway: "192.168.2.254"
        node_dns_server: "192.168.2.254"
        node_cidr: "192.168.2.0/24"
        metallb_ipv4_range: "192.168.2.240-192.168.2.250"

        nfs_paths:
          - {
              name: appdata,
              hostname: pve0.kallan.xyz,
              path: /tank/appdata,
              default: true,
            }
        helm_version: v3.2.4
        ansible_ssh_common_args: "-o ServerAliveInterval=5 -o StrictHostKeyChecking=no"
