production:
  children:
    masters:
      hosts:
        charles:
    workers:
      hosts:
        kingston:
        moss:
  vars:
    # Vars for production go here
    ansible_user: node
    pod_network_cidr: "10.200.0.0/16"
    calico_version: 3.8
