all:
  children:
    proxmox_servers:
      hosts:
        pve1.kallan.xyz:
          k8s_id: "4011"
          k8s_hostname: charles
          k8s_cpu: "2"
          k8s_ip: "192.168.2.201"
          # k8s_stg: CharlesPool
        pve2.kallan.xyz:
          k8s_id: "40101"
          k8s_hostname: kingston
          k8s_cpu: "4"
          k8s_ip: "192.168.2.221"
          # k8s_stg: KingstonPool
        pve3.kallan.xyz:
          k8s_id: "40102"
          k8s_hostname: moss
          k8s_cpu: "4"
          k8s_ip: "192.168.2.222"
          # k8s_stg: MossPool
      vars:
        k8s_mem: "4096"
        k8s_size: "30G"
        k8s_stg: local-lvm
        k8s_reset_vm: yes

    k8s_cluster:
      children:
        k8s_master:
          hosts:
            charles.kallan.xyz:
        k8s_nodes:
          hosts:
            kingston.kallan.xyz:
            moss.kallan.xyz:
      vars:
        ansible_user: debian

  vars:
    # Vars for production go here
    ansible_ssh_common_args: "-o ServerAliveInterval=5 -o StrictHostKeyChecking=no"

    k8s_search_domain: kallan.xyz

    qcow2_image: "https://cdimage.debian.org/cdimage/openstack/current-10/debian-10-openstack-amd64.qcow2"
    qcow2_download_location: "/tmp/"

    k8s_resource_pool: Kubernetes
    k8s_ssh_key: "/root/.ssh/xyz.kallan.pve.kubernetes.pub"

    # Subnet Sizes
    k8s_subnet: "/24"

    # Network Gateway
    k8s_gateway: "192.166.2.254"

    # DNS Servers
    k8s_dns_server: "192.168.2.254"

    # Network Bridges
    k8s_network_bridge: "vmbr0"

    calico_cidr: "172.16.0.0"
    calico_policy_url: "https://docs.projectcalico.org/v3.10/manifests/calico.yaml"

    k8s_dashboard_url: "https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml"
    k8s_user_name: kallan
