all:
  children:
    production:
      children:
        production_masters:
          hosts:
            charles.kallan.xyz:
        production_workers:
          hosts:
            kingston.kallan.xyz:
            moss.kallan.xyz:
    development:
      children:
        development_masters:
          hosts:
            test-ubuntu-1.kallan.xyz:
              # ansible_host: "192.168.2.84"
        development_workers:
          hosts:
            test-ubuntu-2.kallan.xyz:
              # ansible_host: "192.168.2.85"
            test-ubuntu-3.kallan.xyz:
              # ansible_host: "192.168.2.86"
  vars:
    # Vars for production go here
    ansible_user: node
    ansible_python_interpreter: /usr/bin/python3
    domain: kallan.xyz
    pod_network_cidr: "10.200.0.0/16"
    calico_version: "3.10"
    dashboard: yes
    reset: no
