all:
  children:
    proxmox_servers:
      hosts:
        pve0.kallan.xyz:
          tank_disks:
            - "/dev/disk/by-id/ata-ST4000VN000-1H4168_Z306JZKK" #Seagate Ironwolf 4TB
            - "/dev/disk/by-id/ata-ST4000VN008-2DR166_ZDH3MNR2" #Seagate Ironwolf 4TB
          tank_datasets:
            - appdata
          mergerfs_data_disks:
            - {
                name: /mnt/data1,
                source: /dev/disk/by-id/ata-ST4000VN000-1H4168_Z306JHTS,
                fs: xfs,
                key: "1",
              } #Seagate Ironwolf 4TB sde
            - {
                name: /mnt/data2,
                source: /dev/disk/by-id/ata-ST4000VN000-1H4168_Z306F6RS,
                fs: xfs,
                key: "2",
              } #Seagate Ironwolf 4TB sdf
            - {
                name: /mnt/data3,
                source: /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N7ZKL7SX,
                fs: xfs,
                key: "3",
              } #sdc 3TB populated
            # - { name: /mnt/data4, source: /dev/disk/by-id/, fs: xfs, key: "4"} #8TB WDC shucked on order
          mergerfs_parity_disks:
            # - { name: /mnt/parity1, source: /dev/disk/by-id/, fs: xfs, key: "5"} #8TB WDC shucked on order
        pve1.kallan.xyz:
        pve2.kallan.xyz:
        pve3.kallan.xyz:

    nodes:
      children:
        node_master:
          hosts:
            charles.kallan.xyz:
              node_id: "4011"
              node_ip: "192.168.2.201"
              hypervisor: pve1.kallan.xyz
            kingston.kallan.xyz:
              node_id: "4012"
              node_ip: "192.168.2.202"
              hypervisor: pve2.kallan.xyz
            moss.kallan.xyz:
              node_id: "4013"
              node_ip: "192.168.2.203"
              hypervisor: pve3.kallan.xyz
          vars:
            ansible_user: debian
            node_cpu: "4"
            node_mem: "4096"
            node_disk_size: "30G"
            node_stg: local-lvm
            node_resource_pool: Kubernetes
            node_resource_pool_comment: "Kubernetes Control Plane"
            k3s_endpoint: kubernetes.kallan.xyz
        storage:
          hosts:
            beaufort.kallan.xyz:
              node_id: "300"
              node_resource_pool: "Fileservers"
              node_resource_pool_comment: "File Servers"
              node_hostname: beaufort
              node_cpu: "4"
              node_mem: "4096"
              node_ip: "192.168.2.100"
              resource_pool: storage
              hypervisor: pve0.kallan.xyz
      vars:
        node_search_domain: kallan.xyz

        qcow2_image: "https://cdimage.debian.org/cdimage/openstack/current-10/debian-10-openstack-amd64.qcow2"
        qcow2_download_location: "/tmp/"

        node_ssh_key_local: "~/.ssh/xyz.kallan.pve.kubernetes.pub"
        node_ssh_key_remote: "/root/.ssh/xyz.kallan.pve.kubernetes.pub"

        # Subnet Sizes
        node_subnet: "/24"

        # Network
        node_network_bridge: "vmbr0"
        node_gateway: "192.168.2.254"
        node_dns_server: "192.168.2.254"
        node_cidr: "192.168.2.0/24"
        metallb_ipv4_range: "192.168.2.240-192.168.2.250"

        nfs_paths:
          - { name: appdata, hostname: beaufort.kallan.xyz, path: /tank/appdata }
        helm_version: v3.2.4
        ansible_ssh_common_args: "-o ServerAliveInterval=5 -o StrictHostKeyChecking=no"
