all:
  children:
    proxmox_servers:
      hosts:
        pve0.kallan.xyz:
          k8s_id: "40103"
          k8s_hostname: parkwood
          k8s_cpu: "4"
          k8s_ip: "192.168.2.223"
          server_resource_pool: "fileserver"
          server_resource_pool_comment: "File Servers"
          server_id: "300"
          server_hostname: beaufort
          server_cpu: "4"
          server_mem: "4096"
          server_ip: "192.168.2.100"
          resource_pool:
          tank_disks:
            - "/dev/disk/by-id/ata-ST4000VN000-1H4168_Z306JZKK" #Seagate Ironwolf 4TB
            - "/dev/disk/by-id/ata-ST4000VN008-2DR166_ZDH3MNR2" #Seagate Ironwolf 4TB
          tank_datasets:
            - appdata
          mergerfs_data_disks:
            - {
                name: /mnt/data1,
                source: /dev/disk/by-id/ata-ST4000VN000-1H4168_Z306JHTS,
                fs: xfs,
                key: "1",
              } #Seagate Ironwolf 4TB sde
            - {
                name: /mnt/data2,
                source: /dev/disk/by-id/ata-ST4000VN000-1H4168_Z306F6RS,
                fs: xfs,
                key: "2",
              } #Seagate Ironwolf 4TB sdf
            - {
                name: /mnt/data3,
                source: /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N7ZKL7SX,
                fs: xfs,
                key: "3",
              } #sdc 3TB populated
            # - { name: /mnt/data4, source: /dev/disk/by-id/, fs: xfs, key: "4"} #8TB WDC shucked on order
          mergerfs_parity_disks:
            # - { name: /mnt/parity1, source: /dev/disk/by-id/, fs: xfs, key: "5"} #8TB WDC shucked on order
        pve1.kallan.xyz:
          k8s_id: "4011"
          k8s_hostname: charles
          k8s_cpu: "2"
          k8s_ip: "192.168.2.201"
        pve2.kallan.xyz:
          k8s_id: "40101"
          k8s_hostname: kingston
          k8s_cpu: "4"
          k8s_ip: "192.168.2.221"
        pve3.kallan.xyz:
          k8s_id: "40102"
          k8s_hostname: moss
          k8s_cpu: "4"
          k8s_ip: "192.168.2.222"
      vars:
        k8s_mem: "4096"
        k8s_size: "30G"
        k8s_stg: local-lvm

    k8s_cluster:
      children:
        k8s_master:
          hosts:
            charles.kallan.xyz:
        k8s_nodes:
          hosts:
            kingston.kallan.xyz:
            moss.kallan.xyz:
            parkwood.kallan.xyz:
      vars:
        ansible_user: debian

  vars:
    # Vars for production go here
    ansible_ssh_common_args: "-o ServerAliveInterval=5 -o StrictHostKeyChecking=no"

    k8s_search_domain: kallan.xyz

    qcow2_image: "https://cdimage.debian.org/cdimage/openstack/current-10/debian-10-openstack-amd64.qcow2"
    qcow2_download_location: "/tmp/"

    k8s_resource_pool: Kubernetes
    k8s_ssh_key_local: "~/.ssh/xyz.kallan.pve.kubernetes.pub"
    k8s_ssh_key_remote: "/root/.ssh/xyz.kallan.pve.kubernetes.pub"

    # Subnet Sizes
    k8s_subnet: "/24"

    # Network Gateway
    k8s_gateway: "192.168.2.254"

    # DNS Servers
    k8s_dns_server: "192.168.2.254"

    # Network Bridges
    k8s_network_bridge: "vmbr0"
    k8s_cidr: "192.168.2.0"

    calico_cidr: "172.16.0.0"
    calico_policy_url: "https://docs.projectcalico.org/v3.10/manifests/calico.yaml"

    k8s_dashboard_url: "https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml"
    k8s_user_name: kallan

    metallb_ipv4_range: "192.168.2.240-192.168.2.250"

    k8s_nfs_hostname: "192.168.2.176"
    k8s_nfs_path: "/tank/appdata"

    helm_version: v3.2.4
