---

- name: Initialise master nodes
  hosts: masters
  become: yes
  roles:
    - kubernetes-master

- name: Initialise worker nodes
  hosts: workers
  become: yes
  roles:
    - kubernetes-worker

- name: Initialise common roles
  hosts: all
  become: yes
  roles:
    - docker
    - kubernetes-common
    - homelab-cluster
    
# TODO Kubernetes
# kubeadm: the command to bootstrap the cluster.
# kubelet: the component that runs on all of the machines in your cluster and does things like starting pods and containers.
# kubectl: the command line util to talk to your cluster.
