- name: Allow local kubectl
  hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Configuring RBAC for the personal Service Account.
      # become: yes
      k8s:
        definition: "{{ lookup('template', '/workspace/ansible/files/templates/Service_Account/{{ item }}') | from_yaml }}"
      with_items:
        - "sa_personal.yaml.j2"
        - "rb_personal.yaml.j2"

    - name: Retrieving the authentication token for your service user.
      # become: yes
      shell: kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep {{ k8s_user_name }} | awk '{print $1}') | grep 'token:' | awk '{print $2}'
      register: k8s_user_token

    - name: Retreiving the kube config.
      # become: yes
      shell: cat ~/.kube/config
      register: k8s_config

    - name: Creating a local ~/.kube directory on your workstation.
      local_action:
        module: file
        path: ~/.kube
        state: directory

    - name: Copying authentication token to your workstation.
      local_action: copy content={{ k8s_user_token.stdout }} dest=~/.kube/authentication_token

    - name: Copying ~/.kube/config to your workstation.
      local_action: copy content={{ k8s_config.stdout }} dest=~/.kube/config
