---
# Open ports for use by kubernetes

- name: Open control-plane node ports
  hosts: masters
  ufw:
    rule: allow
    direction: incoming
    to_port: "{{ item }}"
    proto: tcp
  loop:
    - 6443 # Kubernetes API server
    - 2379:2380 # etcd server client API
    - 10250 # Kubelet API
    - 10251 # kube-scheduler
    - 10252 # kube-controller-manager
  notify: restart ufw

- name: Open worker node ports
  hosts: workers
  ufw:
    rule: allow
    direction: incoming
    to_port: "{{ item }}"
    proto: tcp
  loop:
    - 10250 # Kubelet API
    - 30000:32767 # NodePort Services
  notify: restart ufw